application/game/__init__.py
from flask import Blueprint, render_template

game_bp = Blueprint('game', __name__, static_folder='static',
                    template_folder='templates', url_prefix='/game')


@game_bp.route("/")
def index():
    return render_template('game/index.html')

application/views.py
import functools

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import generate_password_hash

from application.forms import LoginForm, RegistrationForm
from application.models import Patient, Professional, db

home_bp = Blueprint("home", __name__)


@home_bp.route("/")
def index():
    if current_user.is_authenticated and not hasattr(current_user, "pro_id"):
        pending = Patient.query.filter_by(
            pro_id=current_user.id, prog_group=None
        ).count()
    else:
        pending = 0
    return render_template("index.html", pending=pending)


def logout_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if current_user.is_authenticated:
            flash(
                [f"You are already logged in, {current_user.username}."],
                category="warning",
            )
            return redirect(url_for("home.index"))

        return view(**kwargs)

    return wrapped_view


@home_bp.route("/login", methods=("GET", "POST"))
@logout_required
def login():
    form = LoginForm(request.form)
    if request.method == "POST":
        if form.validate_on_submit():
            user = (
                Patient.query.filter_by(username=form.username.data).first()
                or Professional.query.filter_by(username=form.username.data).first()
            )

            login_user(user, remember=True)
            flash(
                [f"You were successfully logged in, {user.username}."],
                category="success",
            )
            return redirect(url_for("home.index"))

        for error in form.errors.values():
            flash(error, category="danger")

    return render_template("login.html", form=form)


@home_bp.route("/register", methods=("GET", "POST"))
@logout_required
def register():
    form = RegistrationForm(request.form)
    if request.method == "POST":
        if form.validate_on_submit():
            if form.user_type.data == "professional":
                user = Professional(
                    username=form.username.data,
                    password=generate_password_hash(form.password.data),
                )
            else:
                pro_id = (
                    Professional.query.filter_by(username=form.professional.data)
                    .first()
                    .id
                )
                user = Patient(
                    username=form.username.data,
                    password=generate_password_hash(form.password.data),
                    pro_id=pro_id,
                    days_done=0,
                )
            db.session.add(user)
            db.session.commit()
            flash(
                [f"Thanks for registering. You are now logged in."], category="success"
            )
            login_user(user, remember=True)
            return redirect(url_for("home.index"))

        for error in form.errors.values():
            flash(error, category="danger")

    return render_template("register.html", form=form)


@home_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash(["You were successfully logged out."], category="success")
    return redirect(url_for("home.index"))

application/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />

    {% block head %}{% endblock %}

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />

    <!-- Favicon -->
    <link
      rel="icon"
      href="{{ url_for('static', filename='icons/favicon.ico') }}"
      type="image/x-icon"
    />

    <!-- Document's Title -->
    <title>Bleic - {% block title %}{% endblock %}</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('home.index') }}">
          <img
            src="{{ url_for('static', filename='images/logo-xs.png') }}"
            alt="Bleic homepage"
          />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('home.index') }}">Home</a>
            </li>
            {% if current_user.is_authenticated %} {% if current_user.pro_id %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('game.index') }}">Game</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a
                class="nav-link d-flex align-items-center"
                href="{{ url_for('med.patients') }}"
                >Patients{% if not pending|int == 0 %}
                <span class="ms-1 badge text-bg-danger">{{ pending }}</span> {%
                endif %}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('med.routines') }}"
                >Routines</a
              >
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('home.logout') }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('home.register') }}"
                >Register</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('home.login') }}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
        <span class="navbar-text"
          >{% if current_user.is_authenticated %}Logged in:
          <strong>{{ current_user.username }}</strong>{% else %}Not logged in{%
          endif %}</span
        >
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %}
    <div class="m-0 mx-auto" style="max-width: 440px">
      {% for category, message in messages %}
      <div
        class="my-1 alert alert-{{ category }} alert-dismissible fade show text-start"
        role="alert"
      >
        {{ message[0] }}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>
      {% endfor %}
    </div>
    {% endif %} {% endwith %} {% block content %}{% endblock %}

    <!-- Bootstrap JS with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

application/templates/index.html
{% extends "base.html" %} {% block title %}Homepage{% endblock %} {% block
content %}

<div
  class="container my-4 bg-light border border-dark border-3 rounded-3 text-center"
  style="max-width: 720px; --bs-bg-opacity: 0.75"
>
  <img
    class="d-flex mx-auto my-3"
    src="{{ url_for('static', filename='images/logo.png') }}"
  />

  <div class="mx-auto p-3 bg-warning border border-dark border-1">
    <h5 class="m-0">
      The MYO&trade; gesture control armband is required to play this game.
    </h5>
  </div>

  <p class="blockquote my-4">
    This is a video game for upper limb rehabilitation. It is intended to be
    used by people who undergo physical therapy, in cooperation with their
    therapist.
  </p>

  {% if current_user.is_authenticated %}
  <div class="my-3">
    <h3 class="mb-3">Step-by-step instructions:</h3>
    {% if current_user.pro_id %}
    <div class="list-group">
      <div class="list-group-item py-3">
        <div class="w-100">
          <h5 class="mb-1">Download and install Myo Connect</h5>
        </div>
        <div class="row justify-content-center mb-1">
          <div class="col-4">
            <div class="row justify-content-center mt-2">
              <img
                src="{{ url_for('static', filename='images/win.png') }}"
                style="max-width: 80px"
              />
            </div>
            <div class="row justify-content-center mt-2">
              <a
                href="{{ url_for('static', filename='downloads/Myo+Connect+Installer.exe') }}"
                >Myo Connect for Windows</a
              >
            </div>
          </div>
          <div class="col-4">
            <div class="row justify-content-center mt-2">
              <img
                src="{{ url_for('static', filename='images/mac.png') }}"
                style="max-width: 80px"
              />
            </div>
            <div class="row justify-content-center mt-2">
              <a
                href="{{ url_for('static', filename='downloads/MyoConnect.dmg') }}"
                >Myo Connect for macOS</a
              >
            </div>
          </div>
        </div>
      </div>
      <div class="list-group-item py-3">
        <div class="w-100">
          <h5 class="mb-1">Wait for your routine assignment</h5>
        </div>
        <p class="mb-1">
          Your therapist must assign an exercise routine to your user account.
          <br />{% if current_user.prog_group %}
          <span class="fw-bold text-success">Current status: Completed</span>
          {% else %}
          <span class="fw-bold text-danger">Current status: Pending</span>
          {% endif %}
        </p>
      </div>
      <div class="list-group-item py-3">
        <div class="w-100">
          <h5 class="mb-1">Visit the game page to play</h5>
        </div>
        <p class="mb-1">
          Click the Game link in the navigation bar above or the button below:
        </p>
        <a
          class="btn btn-primary w-25"
          href="{{ url_for('game.index') }}"
          role="button"
          >Go to Game</a
        >
      </div>
    </div>
    {% else %}
    <div class="list-group">
      <div class="list-group-item py-3">
        <div class="w-100">
          <h5 class="mb-1">Wait for your patients to register</h5>
        </div>
        <p class="mb-1">
          Your patients must create a user account and submit your username
          during registration.
        </p>
      </div>
      <div class="list-group-item py-3">
        <div class="w-100">
          <h5 class="mb-1">Assign routines to your patients</h5>
        </div>
        <p class="mb-1">
          You must assign an exercise routine to each of your patients using the
          following pages.
          <br />
          <a href="{{ url_for('med.routines') }}">Routines page</a>: Inspect all
          your exercise routines or create a new one as well as your first one.
          <br />
          <a href="{{ url_for('med.patients') }}">Patients page</a>: Check which
          patients are not linked with a routine and charge them with one.
          <br />{% if pending|int == 0 %}
          <span class="fw-bold text-success"
            >Pending assignments: None (0)</span
          >
          {% else %}
          <span class="fw-bold text-danger"
            >Pending assignments: {{ pending }}</span
          >
          {% endif %}
        </p>
      </div>
      <div class="list-group-item py-3">
        <div class="w-100">
          <h5 class="mb-1">Review the sessions of your patients</h5>
        </div>
        <p class="mb-1">
          Through the
          <a href="{{ url_for('med.patients') }}">Patients page</a> you can
          examine reports for each game session of your patients.
        </p>
      </div>
    </div>
    {% endif %}
  </div>
  {% else %}
  <div class="my-3">
    <h4>You need a user account to proceed:</h4>

    <a
      class="btn btn-primary btn-lg mx-1 w-25"
      href="{{ url_for('home.register') }}"
      role="button"
      >Create account</a
    >
    <a
      class="btn btn-primary btn-lg mx-1 w-25"
      href="{{ url_for('home.login') }}"
      role="button"
      >Log in</a
    >
  </div>
  {% endif %}
</div>

{% endblock %}

application/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}

<div
  class="container my-4 bg-light border border-dark border-3 rounded-3 text-center"
  style="max-width: 330px; --bs-bg-opacity: 0.75"
>
  <h1 class="text-uppercase my-3">Login</h1>
  <form method="post">
    {{ form.hidden_tag() }}
    <div class="mb-3">
      {{ form.username.label }} {{ form.username(class="form-control") }}
    </div>
    <div class="mb-3">
      {{ form.password.label }} {{ form.password(class="form-control") }}
    </div>
    <div class="my-4 mx-auto">
      <input type="submit" class="btn btn-primary" value="Submit" />
    </div>
    <div class="mb-3">
      No account?
      <a href="{{ url_for('home.register') }}">Create one!</a>
    </div>
  </form>
</div>

{% endblock %}

application/templates/register.html
{% extends "base.html" %} {% block title %}Register{% endblock %} {% block
content %}

<div
  class="container my-4 bg-light border border-dark border-3 rounded-3 text-center"
  style="max-width: 540px; --bs-bg-opacity: 0.75"
>
  <h1 class="text-uppercase my-3">Register</h1>
  <form method="post">
    {{ form.hidden_tag() }}
    <div class="mb-3">
      {{ form.username.label }} {{ form.username(class="form-control") }}
    </div>
    <div class="mb-3">
      {{ form.password.label }} {{ form.password(class="form-control") }}
    </div>
    <div class="mb-3">
      {{ form.confirm.label }} {{ form.confirm(class="form-control") }}
    </div>
    <div class="mb-3">
      {{ form.user_type.label }}
      <div class="row justify-content-center">
        {% for subfield in form.user_type %}
        <div class="col-1">{{ subfield }} {{ subfield.label }}</div>
        {% endfor %}
      </div>
    </div>
    <div class="mb-3">
      {{ form.professional.label }} {{ form.professional(class="form-control")
      }}
    </div>
    <div class="my-4 mx-auto">
      <input type="submit" class="btn btn-primary" value="Submit" />
    </div>
    <div class="mb-3">
      Already have an account?
      <a href="{{ url_for('home.login') }}">Log in.</a>
    </div>
  </form>
</div>

{% endblock %}